import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import assert from 'node:assert/strict';

// The snapshot is the public feed used by stats.unitedrugby.com, fetched 23 September 2026.
// Re-run only with a complete official source response. This does not fetch private accounts.
const source = JSON.parse(readFileSync('../../fixtures/urc-2026-27-source.json', 'utf8'));
assert(!source.errors, 'The source reported an error');
const rows = source.data.matchstats;
const names = {2019:'benetton-rugby',5586:'vodacom-bulls',4471:'cardiff-rugby',5483:'connacht-rugby',3533:'dragons-rfc',1641:'edinburgh-rugby',3098:'glasgow-warriors',5356:'leinster-rugby',5092:'10bet-lions',4377:'munster-rugby',5057:'ospreys',3514:'scarlets',1527:'hollywoodbets-sharks',3994:'dhl-stormers',2129:'ulster-rugby',4474:'zebre-parma'};
assert.equal(rows.length, 151);
assert.equal(new Set(rows.map(row => row.match_id)).size,151);
const fixtures = rows.map(row => {
  const m = row.stats_data;
  assert(m.round >= 1 && m.round <= 21);
  for (const side of [m.homeTeam.team, m.awayTeam.team]) {
    assert(side.id === null || names[side.id], `Unknown team ${side.name}`);
    if(side.id) assert(existsSync(`public/assets/images/teams/${names[side.id]}.png`));
  }
  assert.equal(row.match_status, 'fixture', 'Review result ingestion before replacing this preseason snapshot');
  return { id:String(row.match_id), round:m.round, homeId:names[m.homeTeam.team.id] ?? null, awayId:names[m.awayTeam.team.id] ?? null,
    kickoffUtc:m.tbc ? null : m.dateTime, dateConfirmed:!m.tbc, venue:m.venue.name === 'TBD' ? null : m.venue.name };
});
for(let round=1; round<=18; round++) assert.equal(fixtures.filter(m=>m.round===round).length,8);
for(const id of Object.values(names)) {
  assert.equal(fixtures.filter(m=>m.homeId===id).length,9);
  assert.equal(fixtures.filter(m=>m.awayId===id).length,9);
}
assert.equal(Date.parse(fixtures.find(m=>m.id==='292599').kickoffUtc),Date.parse('2026-10-03T16:30:00Z'));
assert.equal(Date.parse(fixtures.find(m=>m.id==='292703').kickoffUtc),Date.parse('2027-04-16T17:30:00Z'));
writeFileSync('src/app/urc-fixtures.ts', `// Generated by scripts/import-urc.mjs from the official public URC feed.\nexport const URC_SCHEDULE = ${JSON.stringify({season:'2026/27',source:'https://stats.unitedrugby.com/',feed:'https://www.unitedrugby.com/graphql',retrievedAt:'2026-09-23',fixtures},null,2)} as const;\n`);
console.log('Imported 144 regular-season fixtures and 7 unconfirmed playoff slots. Verified 18 matches per team, 9 home and 9 away.');
