"""Loader for a competition's bundled results of past seasons.

Each competition may name a file (app/competitions/<id>/history.json) and caches the loaded
history itself. The URC file is generated by scripts/import_urc_history.py from the URC
GraphQL feed. Club ids are the competition catalogue's, kickoffs are UTC, and rows with a
team the catalogue does not hold were dropped when the file was written. A competition
without a file has an empty history.
"""

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True)
class PastResult:
    match_id: str
    home_id: str
    away_id: str
    home_score: int
    away_score: int
    kickoff_utc: datetime
    venue: str | None


@dataclass(frozen=True)
class PastSeason:
    season_id: str
    label: str
    results: tuple[PastResult, ...]


@dataclass(frozen=True)
class History:
    source: str
    retrieved_at: str
    seasons: tuple[PastSeason, ...]
    # Every name the feed used for a club, oldest first, by catalogue club id.
    club_names: Mapping[str, tuple[str, ...]]


EMPTY = History("", "", (), {})


def parse_kickoff(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


def load_history(path: Path | None) -> History:
    if path is None:
        return EMPTY
    raw = json.loads(path.read_text(encoding="utf-8"))
    seasons = tuple(
        PastSeason(
            season_id=str(season["seasonId"]),
            label=str(season["label"]),
            results=tuple(
                PastResult(
                    match_id=str(row["matchId"]),
                    home_id=row["homeId"],
                    away_id=row["awayId"],
                    home_score=int(row["homeScore"]),
                    away_score=int(row["awayScore"]),
                    kickoff_utc=parse_kickoff(row["kickoffUtc"]),
                    venue=row.get("venue"),
                )
                for row in season["results"]
            ),
        )
        for season in raw["seasons"]
    )
    names = {club_id: tuple(values) for club_id, values in (raw.get("clubNames") or {}).items()}
    return History(raw["source"], raw["retrievedAt"], seasons, names)
