"""Loader for a competition's bundled schedule file.

Each competition names its file (app/competitions/<id>/schedule.json) and caches the
loaded schedule itself. The URC file is generated by apps/web/scripts/import-urc.mjs from
the same official snapshot the frontend uses. Kickoffs are UTC; unknown kickoffs stay None.
"""

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

@dataclass(frozen=True)
class Fixture:
    id: str
    round: int
    home_id: str | None
    away_id: str | None
    kickoff_utc: datetime | None
    venue: str | None


@dataclass(frozen=True)
class Schedule:
    season: str
    source: str
    retrieved_at: str
    fixtures: tuple[Fixture, ...]

    def fixture(self, fixture_id: str) -> Fixture | None:
        return next((f for f in self.fixtures if f.id == fixture_id), None)

    def round(self, number: int) -> list[Fixture]:
        return [f for f in self.fixtures if f.round == number]


def _parse_kickoff(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


def load_schedule(path: Path) -> Schedule:
    raw = json.loads(path.read_text(encoding="utf-8"))
    fixtures = tuple(
        Fixture(
            id=str(row["id"]),
            round=int(row["round"]),
            home_id=row.get("homeId"),
            away_id=row.get("awayId"),
            kickoff_utc=_parse_kickoff(row.get("kickoffUtc")),
            venue=row.get("venue"),
        )
        for row in raw["fixtures"]
    )
    return Schedule(raw["season"], raw["source"], raw["retrievedAt"], fixtures)
